# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/wentworth/Desktop/skeaf_demo_sw/skeaf_demo_2/B_direction.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_B_direction(object):
    def setupUi(self, B_direction):
        B_direction.setObjectName("B_direction")
        B_direction.resize(427, 123)
        self.gridLayout = QtWidgets.QGridLayout(B_direction)
        self.gridLayout.setObjectName("gridLayout")
        self.B_direction_layout = QtWidgets.QGridLayout()
        self.B_direction_layout.setObjectName("B_direction_layout")
        self.Theta_layout = QtWidgets.QGridLayout()
        self.Theta_layout.setObjectName("Theta_layout")
        self.Theta_label = QtWidgets.QLabel(B_direction)
        self.Theta_label.setObjectName("Theta_label")
        self.Theta_layout.addWidget(self.Theta_label, 0, 0, 1, 1)
        self.Theta_line = QtWidgets.QLineEdit(B_direction)
        self.Theta_line.setObjectName("Theta_line")
        self.Theta_layout.addWidget(self.Theta_line, 0, 1, 1, 1)
        self.Theta_layout.setColumnStretch(0, 1)
        self.Theta_layout.setColumnStretch(1, 2)
        self.B_direction_layout.addLayout(self.Theta_layout, 0, 0, 1, 1)
        self.seperate_line = QtWidgets.QFrame(B_direction)
        self.seperate_line.setFrameShape(QtWidgets.QFrame.VLine)
        self.seperate_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.seperate_line.setObjectName("seperate_line")
        self.B_direction_layout.addWidget(self.seperate_line, 0, 1, 2, 1)
        self.b_layout = QtWidgets.QGridLayout()
        self.b_layout.setObjectName("b_layout")
        self.b1_layout = QtWidgets.QGridLayout()
        self.b1_layout.setObjectName("b1_layout")
        self.b1_label = QtWidgets.QLabel(B_direction)
        self.b1_label.setObjectName("b1_label")
        self.b1_layout.addWidget(self.b1_label, 0, 0, 1, 1)
        self.b1_line = QtWidgets.QLineEdit(B_direction)
        self.b1_line.setObjectName("b1_line")
        self.b1_layout.addWidget(self.b1_line, 0, 1, 1, 1)
        self.b_layout.addLayout(self.b1_layout, 0, 0, 1, 1)
        self.b2_layout = QtWidgets.QGridLayout()
        self.b2_layout.setObjectName("b2_layout")
        self.b2_line = QtWidgets.QLineEdit(B_direction)
        self.b2_line.setObjectName("b2_line")
        self.b2_layout.addWidget(self.b2_line, 0, 1, 1, 1)
        self.b2_label = QtWidgets.QLabel(B_direction)
        self.b2_label.setObjectName("b2_label")
        self.b2_layout.addWidget(self.b2_label, 0, 0, 1, 1)
        self.b_layout.addLayout(self.b2_layout, 0, 1, 1, 1)
        self.b3_layout = QtWidgets.QGridLayout()
        self.b3_layout.setObjectName("b3_layout")
        self.b3_label = QtWidgets.QLabel(B_direction)
        self.b3_label.setObjectName("b3_label")
        self.b3_layout.addWidget(self.b3_label, 0, 0, 1, 1)
        self.b3_line = QtWidgets.QLineEdit(B_direction)
        self.b3_line.setObjectName("b3_line")
        self.b3_layout.addWidget(self.b3_line, 0, 1, 1, 1)
        self.b_layout.addLayout(self.b3_layout, 0, 2, 1, 1)
        self.B_direction_layout.addLayout(self.b_layout, 0, 2, 2, 1)
        self.Phi_layout = QtWidgets.QGridLayout()
        self.Phi_layout.setObjectName("Phi_layout")
        self.Phi_label = QtWidgets.QLabel(B_direction)
        self.Phi_label.setObjectName("Phi_label")
        self.Phi_layout.addWidget(self.Phi_label, 0, 0, 1, 1)
        self.Phi_line = QtWidgets.QLineEdit(B_direction)
        self.Phi_line.setObjectName("Phi_line")
        self.Phi_layout.addWidget(self.Phi_line, 0, 1, 1, 1)
        self.Phi_layout.setColumnStretch(0, 1)
        self.Phi_layout.setColumnStretch(1, 2)
        self.B_direction_layout.addLayout(self.Phi_layout, 1, 0, 1, 1)
        self.B_direction_layout.setColumnStretch(0, 1)
        self.B_direction_layout.setColumnStretch(1, 1)
        self.B_direction_layout.setColumnStretch(2, 2)
        self.gridLayout.addLayout(self.B_direction_layout, 0, 0, 1, 1)
        self.updateB_button = QtWidgets.QPushButton(B_direction)
        self.updateB_button.setObjectName("updateB_button")
        self.gridLayout.addWidget(self.updateB_button, 1, 0, 1, 1)

        self.retranslateUi(B_direction)
        QtCore.QMetaObject.connectSlotsByName(B_direction)

    def retranslateUi(self, B_direction):
        _translate = QtCore.QCoreApplication.translate
        B_direction.setWindowTitle(_translate("B_direction", "B direction"))
        self.Theta_label.setText(_translate("B_direction", "Theta"))
        self.b1_label.setText(_translate("B_direction", "b1"))
        self.b2_label.setText(_translate("B_direction", "b2"))
        self.b3_label.setText(_translate("B_direction", "b3"))
        self.Phi_label.setText(_translate("B_direction", "Phi"))
        self.updateB_button.setText(_translate("B_direction", "Update B direction"))
